doctrine:
    dbal:
        driver:  pdo_sqlite
        path: '%kernel.project_dir%/var/data/db.sqlite'
        memory:  false
        charset: UTF8
        logging: false

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Entity'
                alias: App
